### ISSUE TITLE
Mouse input?

### ISSUE THREAD

**Issue by pupdeg** [tqphan/EyeBind#1]
Just found this repo, it's very useful even in 2024, I'm using it with a Tobii eye tracker 5 with no problems. 

Probably a long shot, but is there any way to get this to send mouse commands via profile xml modification? I know it's designed for keyboard, but it does have some mouse functionality, it'd be useful to send clicks on blink or scroll inputs on gaze.

**Comment by tqphan** [comment]
@pupdeg 
The WindowsInput library used by this project supports mouse simulations. It will require modifications to the source code. It can't be done with just XML modification. It's unlikely that I find the motivation to implement new features to this old project.

The good news is that you have a couple of options to achieve what you want.

1. You can use AutoHotkey to bind a key generated by EyeBind to mouse commands. If you need detailed information on how to make this work, let me know.
2. Migrate to OptiKey as it has a feature called Gestures that's similar to EyeBind.

**Comment by pupdeg** [comment]
Thanks for the reply. I've started using AHK in combination with it, which works well enough for what I need.
